# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        types:
          - python
      - id: end-of-file-fixer
        types:
          - python
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys, --expand-star-imports]
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=120
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.0
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus

  - repo: https://github.com/psf/black
    rev: 21.5b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: py3.9
        args:
          - --line-length=120
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        args:
          - --max-line-length=120
          - --extend-ignore=E203, W503, F405, B009, B010, B015, SIM105, SIM106, SIM119

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.8
    hooks:
      - id: commitizen
        stages: [commit-msg]